export  const STOLEN_BIKES_FETCH = 'STOLEN_BIKES_FETCH';
export  const STOLEN_BIKES_REQUEST = 'STOLEN_BIKES_REQUEST';
export  const STOLEN_BIKES_ERROR = 'STOLEN_BIKES_ERROR';
export  const STOLEN_BIKES_FILTERED = 'STOLEN_BIKES_FILTERED';

